### ISSUE TITLE
What is the principle for entering a quota??? 

### ISSUE THREAD

**Issue by ayton** [yiguihai/shadowsocks_install#1]
Hi. I can't pass this point, no matter what quota I entered, the installation stops.

-----------------------------------------------------
请输入端口流量配额 (MB) : 2000000
./shadowsocks-libev.sh: line 355: [: too many arguments
./shadowsocks-libev.sh: line 355: [: too many arguments

20000
00 MB
ok
./shadowsocks-libev.sh: line 369: 20000
00: syntax error in expression (error token is "00")

-----------------------------------------------------
What is the principle for entering a quota??? 
I need to allocate 2TB of traffic to the user.
Thanks...

**Comment by yiguihai** [comment]
你的输入不能大于999999
Your input cannot be greater than 999999

**Comment by yiguihai** [comment]
> Hi. I can't pass this point, no matter what quota I entered, the installation stops.
> 
> 请输入端口流量配额 (MB) : 2000000
> ./shadowsocks-libev.sh: line 355: [: too many arguments
> ./shadowsocks-libev.sh: line 355: [: too many arguments
> 
> 20000
> 00 MB
> ok
> ./shadowsocks-libev.sh: line 369: 20000
> 00: syntax error in expression (error token is "00")
> 
> What is the principle for entering a quota???
> I need to allocate 2TB of traffic to the user.
> Thanks...
你的输入不能大于999999
Your input cannot be greater than 999999

**Comment by yiguihai** [comment]
> Hi. I can't pass this point, no matter what quota I entered, the installation stops.
> 
> 请输入端口流量配额 (MB) : 2000000
> ./shadowsocks-libev.sh: line 355: [: too many arguments
> ./shadowsocks-libev.sh: line 355: [: too many arguments
> 
> 20000
> 00 MB
> ok
> ./shadowsocks-libev.sh: line 369: 20000
> 00: syntax error in expression (error token is "00")
> 
> What is the principle for entering a quota???
> I need to allocate 2TB of traffic to the user.
> Thanks...

你的输入不能大于999999
Your input cannot be greater than 999999

**Comment by ayton** [comment]
Thanks...
