### ISSUE TITLE
any blog tutorial for this repo?

### ISSUE THREAD

**Issue by malikshi** [yiguihai/shadowsocks_install#1]
I need EN translation or tutorial installation setting

**Comment by yiguihai** [comment]
> I need EN translation or tutorial installation setting

Can you help me translate this shell script into English?

**Comment by malikshi** [comment]
> Can you help me translate this shell script into English?

I don't really understand CN language. Translation with google would be bad idea.

**Comment by yiguihai** [comment]
> > Can you help me translate this shell script into English?
> 
> I don't really understand CN language. Translation with google would be bad idea.

I will translate it into English there may be some grammatical expression errors can you help me fix it?
