### ISSUE TITLE
can't make video calls WhatsApp

### ISSUE THREAD

**Issue by ayton** [yiguihai/shadowsocks_install#1]
Hi, thanks for the script, everything works fine, but unfortunately video calls do not go through, can you somehow help solve this?
I have configured v2ray quic + tls. 
Thanks...

**Comment by yiguihai** [comment]
> Hi, thanks for the script, everything works fine, but unfortunately video calls do not go through, can you somehow help solve this?
> I have configured v2ray quic + tls.
> Thanks...

Shadowsocks-libev does not support udp protocol forwarding in plug-in mode.
