### ISSUE TITLE
i got an error

### ISSUE THREAD

**Issue by malikshi** [yiguihai/shadowsocks_install#3]
after done installation. i tried to turn on services and need to add active port then turn on the services. and try add port again but this error come up
>/tmp/tmp.ONl97zToQD/ss-main: line 862: column: command not found

**Comment by yiguihai** [comment]
> after done installation. i tried to turn on services and need to add active port then turn on the services. and try add port again but this error come up
> 
> > /tmp/tmp.ONl97zToQD/ss-main: line 862: column: command not found

What system and version are you using?

**Comment by malikshi** [comment]
> > after done installation. i tried to turn on services and need to add active port then turn on the services. and try add port again but this error come up
> > > /tmp/tmp.ONl97zToQD/ss-main: line 862: column: command not found
> 
> What system and version are you using?

ubuntu 20.04 and kernel 5.11 custom bbr plus.

**Comment by yiguihai** [comment]
> > > after done installation. i tried to turn on services and need to add active port then turn on the services. and try add port again but this error come up
> > > > /tmp/tmp.ONl97zToQD/ss-main: line 862: column: command not found
> > 
> > 
> > What system and version are you using?
> 
> ubuntu 20.04 and kernel 5.11 custom bbr plus.

I'm using debian 10 and have never used such a new system. You can try 
```Bash
apt-get install bsdmainutils
```

**Comment by malikshi** [comment]
`apt-get install bsdmainutils`
thank you. solved now. did `bsdmainutils` miss from the installation script?

**Comment by yiguihai** [comment]
> `apt-get install bsdmainutils`
> thank you. solved now. did `bsdmainutils` miss from the installation script?

I've been using debian so I don't have time to adapt to other systems.
It's fixed now, just wait for CI to finish and update in ss-main

**Comment by malikshi** [comment]
thank you very much, it's a fast problem-solving

**Comment by malikshi** [comment]
@yiguihai sir i want to ensure abour systemd ss-main
`systemctl restart ss-main`
It's frozen?
Usually the way restart like this one
>root @ vps: systemctl restart blabla.service
root @ vps:

But for ss-main become stuck/frozen
>root @ vps : systemctl restart ss-main.service
>

It's doesn't back to `root @ vps :` need to CTRL + C but the checking `systemctl status ss-main` it's restarted when looking at time active
