### ISSUE TITLE
Debian11用户列表显示乱码信息

### ISSUE THREAD

**Issue by HSK077** [yiguihai/shadowsocks_install#5]
作者你好：
我发现debian11系统下，用户列表会出现乱码信息
![Snipaste_2021-08-25_08-41-01](https://user-images.githubusercontent.com/54111827/130708092-5eefec84-a736-489f-85ea-716adf6269ce.png)

提个建议增加新的伪装模块
https://popxi.click/

**Comment by yiguihai** [comment]
> 作者你好：
> 我发现debian11系统下，用户列表会出现乱码信息
> ![Snipaste_2021-08-25_08-41-01](https://user-images.githubusercontent.com/54111827/130708092-5eefec84-a736-489f-85ea-716adf6269ce.png)
> 
> 提个建议增加新的伪装模块
> https://popxi.click/

1. 目前在用Debian10我也不知道怎么办...  
代码是直接复制粘贴的我自己也没有看明白，
https://github.com/yiguihai/shadowsocks_install/blob/8bbd536d77ca418db8664b857527a6b95299343c/src/manager.sh#L798-L881
2. 没有提供项目源码

**Comment by HSK077** [comment]
英文模式下显示正常，看我是我dd装的系统问题，感谢回复！
