### ISSUE TITLE
开启nginx出现以下错误信息

### ISSUE THREAD

**Issue by HSK077** [yiguihai/shadowsocks_install#6]
操作系统：debian10/11 （商家版/纯净版都测试过）
之前第一次用的时候是正常的
![Snipaste_2021-09-22_17-28-52](https://user-images.githubusercontent.com/54111827/134320352-1f3ec05c-5b90-4bb6-9652-cf3061b06f30.png)
![Snipaste_2021-09-22_16-43-07](https://user-images.githubusercontent.com/54111827/134320363-ee6b7cb5-2c30-42b2-bdb1-cdc07d4fa599.png)

**Comment by yiguihai** [comment]
> 操作系统：debian10/11 （商家版/纯净版都测试过）
> 之前第一次用的时候是正常的
> ![Snipaste_2021-09-22_17-28-52](https://user-images.githubusercontent.com/54111827/134320352-1f3ec05c-5b90-4bb6-9652-cf3061b06f30.png)
> ![Snipaste_2021-09-22_16-43-07](https://user-images.githubusercontent.com/54111827/134320363-ee6b7cb5-2c30-42b2-bdb1-cdc07d4fa599.png)
第一副图看起来是443端口被占用了，你应该排查一下那个程序占用了443端口。  
第二副图错误为找不到v2ray的配置或者没有脚本写出配置。  
你可以在脚本用选择关闭Nginx多执行几次在开启Nginx
不行就重启服务器之后再在脚本中开启Nginx

**Comment by yiguihai** [comment]
> 操作系统：debian10/11 （商家版/纯净版都测试过）
> 之前第一次用的时候是正常的
> ![Snipaste_2021-09-22_17-28-52](https://user-images.githubusercontent.com/54111827/134320352-1f3ec05c-5b90-4bb6-9652-cf3061b06f30.png)
> ![Snipaste_2021-09-22_16-43-07](https://user-images.githubusercontent.com/54111827/134320363-ee6b7cb5-2c30-42b2-bdb1-cdc07d4fa599.png)

第一副图看起来是443端口被占用了，你应该排查一下那个程序占用了443端口。
第二副图错误为找不到v2ray的配置或者没有脚本写出配置。
你可以在脚本用选择关闭Nginx多执行几次在开启Nginx
不行就重启服务器之后再在脚本中开启Nginx
