### ISSUE TITLE
ss-main terminated

### ISSUE THREAD

**Issue by malikshi** [yiguihai/shadowsocks_install#7]
Ubuntu 20.04
```ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.11  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::f816:3eff:feb5:ca3b  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:b5:ca:3b  txqueuelen 1000  (Ethernet)
        RX packets 2815092  bytes 3105595265 (3.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1209098  bytes 1996381224 (1.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

error log

```
从本机获取到的IP地址不是公网地址！
Terminated
```

how the script get the IP? can just using `IP="$(curl https://api.ipify.org -sS)"` can find public IP behind NAT

**Comment by yiguihai** [comment]
> Ubuntu 20.04
> 
> ```
>         inet 10.0.0.11  netmask 255.255.255.0  broadcast 10.0.0.255
>         inet6 fe80::f816:3eff:feb5:ca3b  prefixlen 64  scopeid 0x20<link>
>         ether fa:16:3e:b5:ca:3b  txqueuelen 1000  (Ethernet)
>         RX packets 2815092  bytes 3105595265 (3.1 GB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1209098  bytes 1996381224 (1.9 GB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> ```
> 
> error log
> 
> ```
> 从本机获取到的IP地址不是公网地址！
> Terminated
> ```
> 
> how the script get the IP? can just using `IP="$(curl https://api.ipify.org -sS)"` can find public IP behind NAT

https://github.com/yiguihai/shadowsocks_install/blob/313a63c7117e760307ca12b9c0652ec7ab162109/src/manager.sh#L441-L477

**Comment by malikshi** [comment]
![image](https://user-images.githubusercontent.com/9080737/135720627-f87d387e-3a81-4b86-ae44-29ffe15a459f.png)
I see, that why can't found the public IPv4 from NAT VPS you may use curl instead.

**Comment by yiguihai** [comment]
> ![image](https://user-images.githubusercontent.com/9080737/135720627-f87d387e-3a81-4b86-ae44-29ffe15a459f.png) I see, that why can't found the public IPv4 from NAT VPS you may use curl instead.
> 
> ```shell
> root@cpanel:~# IP="$(curl https://api.ipify.org -sS)"
> root@cpanel:~# echo $IP
> 103.150.xxx.xxx
> ```



> ![image](https://user-images.githubusercontent.com/9080737/135720627-f87d387e-3a81-4b86-ae44-29ffe15a459f.png) I see, that why can't found the public IPv4 from NAT VPS you may use curl instead.
> 
> ```shell
> root@cpanel:~# IP="$(curl https://api.ipify.org -sS)"
> root@cpanel:~# echo $IP
> 103.150.xxx.xxx
> ```

Do not consider supporting NAT VPS

**Comment by malikshi** [comment]
>@yiguihai Do not consider supporting NAT VPS

since you don't want to add support server VPS behind NAT then I should say thank you and bye.
